# Generated by Django 3.2 on 2021-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Place', models.CharField(max_length=20)),
                ('Photo', models.ImageField(upload_to='')),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
