# Generated by Django 3.2 on 2021-04-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
