# Generated by Django 3.2 on 2021-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.ImageField(upload_to='media/')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
