# Generated by Django 3.2 on 2021-04-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='File',
        ),
        migrations.AddField(
            model_name='gallery',
            name='Photo1',
            field=models.ImageField(default='SOME STRING', upload_to='media2/'),
        ),
    ]
